version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - ./:/app/log_parser
      - app_poetry:/root/.cache/pypoetry
    working_dir: /app/log_parser
    environment:
      - PYTHONPATH=/app/log_parser
    tty: true
    stdin_open: true

volumes:
  app_poetry:
    external: false
