version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    tty: true
    stdin_open: true
