aws_access_key: 'minio'
aws_secret_access_key: 'minio123'
aws_endpoint_url: !ENV ${DUMMY_ENDPOINT_URL}

aws_application_load_balancer:
  - name: sample # unique and snake_case
    account_id: 123456789012
    region: ap-northeast-1
    bucket: log-parser-test
    prefix: sample # prefix to AWSLogs. ex) s3://log-parser-test/sample/AWSLogs/123456789012/ → sample
    target_datetime: 2023/12/28 21:58 # target utc datetime. ex) 2023/12/31 15:00

aws_cloudwatch_metric:
  - account_id: 453701783227
    region: ap-northeast-1
    start_time: 2024/01/18 12:40:00 # 2024/01/05 06:10:00
    end_time: 2024/01/05 13:00:00 # 2024/01/05 06:20:00
    timezone: Asia/Tokyo # Asia/Tokyo
    metrics:
      - id: sample
        namespace: AWS/ApplicationELB
        name: RequestCount
        stat: Sum
        dimensions:
          - name: Resource
            value: sample
