aws_access_key: 'minio'
aws_secret_access_key: 'minio123'
aws_endpoint_url: !ENV ${DUMMY_ENDPOINT_URL}
aws_role_arn:  # Set Role arn, when use switch role.
aws_mfa_arn:  # Set MFA device arn, when Role arn is setted.

aws_application_load_balancer:
  - name: sample # unique and snake_case
    account_id: 123456789012
    region: ap-northeast-1
    bucket: log-parser-test
    prefix: sample # prefix to AWSLogs. ex) s3://log-parser-test/sample/AWSLogs/123456789012/ → sample
    target_datetime: 2023/12/28 21:58 # target utc datetime. ex) 2023/12/31 15:00

aws_cloudwatch_metric:
  - account_id: 123456789012
    region: ap-northeast-1
    start_time: 2024/01/18 12:40:00 # 2024/01/05 06:10:00
    end_time: 2024/01/18 13:00:00 # 2024/01/05 06:20:00
    timezone: Asia/Tokyo # Asia/Tokyo
    period: 300 # seconds
    filename: sample # filename without extension. ex) request_count.tsv → request_count
    metrics:
      - id: alb_request_count
        namespace: AWS/ApplicationELB
        name: RequestCount
        stat: Sum
        dimensions:
          - name: LoadBalancer
            value: sample
  - account_id: 123456789012
    region: ap-northeast-1
    start_time: 2024/01/18 12:40:00 # 2024/01/05 06:10:00
    end_time: 2024/01/18 13:00:00 # 2024/01/05 06:20:00
    timezone: Asia/Tokyo # Asia/Tokyo
    period: 300 # seconds
    filename: sample # filename without extension. ex) request_count.tsv → request_count
    metrics:
      - id: alb_request_count
        namespace: AWS/ApplicationELB
        name: RequestCount
        stat: Sum
        dimensions:
          - name: LoadBalancer
            value: sample
      - id: alb_request_count_200
        namespace: AWS/ApplicationELB
        name: HTTPCode_Target_2XX_Count
        stat: Sum
        dimensions:
          - name: LoadBalancer
            value: sample

tools:
  metrics_dict_creation:
    region: ap-northeast-1
    namespaces:
      - AWS/EC2
