aws_access_key: 'minio'
aws_secret_access_key: 'minio123'
aws_endpoint_url: !ENV ${AWS_ENDPOINT_URL}

aws_application_load_balancer:
  - name: sample # unique and snake_case
    account_id: 123456789012
    region: ap-northeast-1
    bucket: log-parser-test
    prefix: sample # prefix to AWSLogs. ex) s3://log-parser-test/sample/AWSLogs/123456789012/ → sample
    target_datetime: 2023/12/28 21:58 # target utc datetime. ex) 2023/12/31 15:00
